### ISSUE TITLE
Errors on save / compile / serial monitor (seems originated by special characters in windows username)

### ISSUE THREAD

**Issue by JulianLorenzon** [platformio/platform-espressif8266#36]
My windows user path is as follows: C:/Users/Serial'S/
That does not seem to go well with Atom / PlatformIO

2 of the errors i get are:
"C:/Users/Serial&#039;S/.platformio/packages/toolchain-xtensa/bin/xtensa-lx106-elf-g++.exe" not found
Note it should be:
"C:/Users/Serial'S/.platformio/packages/toolchain-xtensa/bin/xtensa-lx106-elf-g++.exe"

ess.target.send (internal/child_process.js:540:16)
at Task.module.exports.Task.send (C:\Users\Serial'S\AppData\Local\atom\app-1.17.2\resources\app\src\task.js:119:1)
at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (file:///C:/Users/Serial'S/.atom/packages/platformio-ide-terminal/lib/view.coffee:264:17)
at Terminal. (file:///C:/Users/Serial'S/.atom/packages/platformio-ide-terminal/lib/view.coffee:142:8)
at Terminal.EventEmitter.emit (C:\Users\Serial'S.atom\packages\build\node_modules\term.js\src\term.js:109:12)
at Terminal.handler (C:\Users\Serial'S.atom\packages\build\node_modules\term.js\src\term.js:3493:8)
at Terminal.keyPress (C:\Users\Serial'S.atom\packages\build\node_modules\term.js\src\term.js:3243:8)
at HTMLDocument. (C:\Users\Serial'S.atom\packages\build\node_modules\term.js\src\term.js:608:29)

Any idea how could i go from here?

This is when dealing with an esp8266 project

Thanks in advance
Julián

**Comment by ivankravets** [comment]
Could you reproduce this issue with the latest PIO Core?
